# Generated by Django 5.1.2 on 2024-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='status',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
