# Generated by Django 5.1.2 on 2024-11-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_jobpost_status_jobpost_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='message',
            new_name='content',
        ),
    ]
