# Generated by Django 5.1.2 on 2024-11-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_jobseeker_cv_jobseeker_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='cv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
